language: cpp
compiler: gcc
sudo: required
dist: xenial

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt562-xenial -y
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install mesa-common-dev libglu1-mesa-dev qt56base qt56tools qt56svg
  - source /opt/qt*/bin/qt*-env.sh
  - git clone git://github.com/ksnip/kColorPicker
  - cd kColorPicker
  - mkdir build && cd build
  - cmake ..
  - make && sudo make install
  - cd ../..

jobs:
  include:
    - stage: build
      script:
        - mkdir build ; cd build
        - cmake .. ; make VERBOSE=1
    - stage: test
      script:
        - mkdir build ; cd build
        - cmake .. -DBUILD_TESTS=ON ; make
        - xvfb-run make test CTEST_OUTPUT_ON_FAILURE=1